server:
  port: 8888
spring:
  application:
    name: camargos-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Leandro-Camargos/config-server
#          username:
#          password:
          default-label: main
          search-paths:
            - 'greeting-service*'