server:
  port: 8080
spring:
  application:
    name: greeting-service
  config:
    import: optional:configserver:http://localhost:8888/ #usando o projeto config-server com configs no GITHUB
  cloud:
    config:
      profile: prod
#Parte responsável pelo Actuator
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
greeting-service:
  greeting: "olá"
  default-value: "Mundo"